inputs:
  bun-version:
    description: The version of Bun to use
    required: true

name: bun install
description: Setup Bun and install dependencies.
runs:
  using: composite
  steps:
    - name: Set up swap space
      if: runner.os == 'Linux'
      uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: 10

    - name: Use Bun Latest
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: bun install --immutable
