name: build

on:
  workflow_call:
    inputs:
      bun-version:
        description: The version of Bun to use (default `latest`)
        required: false
        default: latest
        type: string
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string
      with-submodules:
        description: Whether to include submodules when checking out the repository (default `false`)
        required: false
        default: 'false'
        type: string

jobs:
  build:
    name: Building
    uses: zendrex/zendrex/.github/workflows/reusable-bun-job.yml@main
    with:
      script-name: build
      operating-system: ${{ inputs.operating-system }}
      bun-version: ${{ inputs.bun-version }}
      with-submodules: ${{ inputs.with-submodules }}
