name: Run Bun job

on:
  workflow_call:
    inputs:
      bun-version:
        description: The version of Bun to use (default `latest`)
        required: false
        default: latest
        type: string
      operating-system:
        description: The operating system to use (default `ubuntu-latest`)
        required: false
        default: ubuntu-latest
        type: string
      with-submodules:
        description: Whether to include submodules when checking out the repository (default `false`)
        required: false
        default: 'false'
        type: string
      script-name:
        description: The name of the bun script to run
        required: true
        type: string
    secrets:
      NPM_AUTH_TOKEN:
        description: The token to authenticate with the NPM registry
        required: false

jobs:
  run-job:
    name: Run Script
    runs-on: ${{ inputs.operating-system }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.with-submodules }}
      - name: Fetch NPMRC Artifact
        uses: actions/download-artifact@v4
        with:
          name: npmrc
          path: .
      - name: Install Dependencies
        uses: zendrex/zendrex/.github/actions/install-bun-dependencies@main
        with:
          bun-version: ${{ inputs.bun-version }}
      - name: Run Script
        run: bun run ${{ inputs.script-name }}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
